### ISSUE TITLE
Failed to download budget: Could not get remote files

### ISSUE THREAD

**Issue by thewinger** [sakowicz/actual-ai#139]
**Actual Client version: v25.1.0
Actual Server version: v25.1.0**

```yaml
actual_server:
  container_name: actual
  image: docker.io/actualbudget/actual-server:latest
  networks:
    - t2_proxy
  restart: unless-stopped
  ports:
    - "5006:5006"
  volumes:
    - $DOCKERDIR/actual-data
```
**@sakowicz/actual-ai@1.7.5 prod**

```yaml
actual-ai:
  image: docker.io/sakowicz/actual-ai:latest
  container_name: actual-ai
  restart: unless-stopped
  networks:
    - t2_proxy
  depends_on:
    - actual_server
  environment:
    ACTUAL_SERVER_URL: <actual-server-url>
    ACTUAL_PASSWORD: <password>
    ACTUAL_BUDGET_ID: <sync-id>
    CLASSIFICATION_SCHEDULE_CRON: 0 0 * * *
    CLASSIFY_ON_STARTUP: "true" 
    SYNC_ACCOUNTS_BEFORE_CLASSIFY: "true"
    LLM_PROVIDER: google-generative-ai 
    GOOGLE_GENERATIVE_AI_API_KEY: $GOOGLE_GENERATIVE_AI_API_KEY 
    GOOGLE_GENERATIVE_AI_MODEL: "gemini-1.5-flash" "https://generativelanguage.googleapis.com".
    GOOGLE_GENERATIVE_AI_BASE_URL: https://generativelanguage.googleapis.com
```

**Error**
```
> @sakowicz/actual-ai@1.7.5 prod
> node dist/app.js
Creating model for provider: google-generative-ai
Application started
Starting classification process
Failed to download budget: Could not get remote files
An error occurred: Error: Budget download failed
    at ActualApiService.initializeApi (/opt/node_app/app/dist/src/actual-api-service.js:40:19)
    at async ActualAiService.classify (/opt/node_app/app/dist/src/actual-ai.js:16:13)
    at async /opt/node_app/app/dist/app.js:19:9
/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:37684
                        throw new Error('Could not get remote files');
                              ^
Error: Could not get remote files
    at handlers.api/download-budget (/opt/node_app/node_modules/@actual-app/api/dist/app/bundle.api.js:37684:31)
Node.js v18.20.6
```

For `<actual-server-url>` I have tried the formats https://actual.server-url, http://local-server-ip:5006 and http://container-ip:5006, but still have the same error.

I created a local node project with the api code from this [help file](https://actualbudget.org/docs/api/) and using https://actual.server-url and I fetched the data. So not sure what is failing.

**Comment by sakowicz** [comment]
It is really hard to say without knowing the exact configuration setting.

The containers should be inside the same network if they are on the same host. Then use `container_name:5006` or `service_name:5006`.
If you are using the same `docker-compose.yml` use `ACTUAL_SERVER_URL: http://actual_server:5006`
If you are using separate `docker-compose.yml`, use `ACTUAL_SERVER_URL: http://actual:5006` and make sure that `t2_proxy` is external in one or two `docker-compose.yml` (depending on the place when it is declared).

**Comment by thewinger** [comment]
Everything is in the same docker-compose.yml, tried with `ACTUAL_SERVER_URL: http://actual_server:5006` but receiving the same error.
Looking at actual-ai container info in Portainer I see that it's not getting IP from t2_proxy:

![Image](https://github.com/user-attachments/assets/45615bca-483a-45cc-bb85-d139e8af994f)

And I can't try to ping from the actual-ai container because it says all the time it is restarting.

**Comment by sakowicz** [comment]
Try to create a new network just for these services, like that:

```
services:
  actual_server:
    networks:
      - t2_proxy
      - actual

  actual-ai:
    networks:
      - t2_proxy
      - actual

networks:
  actual:

```

Btw you have misconfigured
```
    GOOGLE_GENERATIVE_AI_MODEL: "gemini-1.5-flash" "https://generativelanguage.googleapis.com".
```
