### ISSUE TITLE
No classification happening - ollama.

### ISSUE THREAD

**Issue by smathev** [sakowicz/actual-ai#194]
I'm having trouble getting actual-ai to classify anything.

I should be running the latest ollama, actual-ai and actualbudget per my compose-files.

These are my ActualBudget containers in their compose.yml file:
```
name: actualbudget

include:
  - path: ../config/networks.yml

services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    networks:
      - internal_services
    volumes:
      - ${HOME_DOCKER_CONFIG}/actualbudget/actual-data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    labels:
      caddy-int: ${ACTUALBUDGET_DOMAIN}
      caddy-int.reverse_proxy: "{{upstreams 5006}}"
      caddy-int.tls: internal

  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    restart: unless-stopped
    networks:
      - internal_services
    environment:
      ACTUAL_SERVER_URL: https://******
      ACTUAL_PASSWORD: ******
      ACTUAL_BUDGET_ID: e21d37ea-0d40-4be1-afaa-a71403dc918b
      CLASSIFICATION_SCHEDULE_CRON: "*/4 * * * *"
      CLASSIFY_ON_STARTUP: true
      SYNC_ACCOUNTS_BEFORE_CLASSIFY: false
      LLM_PROVIDER: ollama
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      OLLAMA_BASE_URL: http://ollama:11434/api
      OLLAMA_MODEL: phi4-mini
      NOT_GUESSED_TAG: "#actual-ai-miss"
      GUESSED_TAG: "#actual-ai"

```
And, this is my ollama compose-file:

```
name: ollama_stack

include:
  - path: ../config/networks.yml

services:
  ollama:
    image: ollama/ollama:latest
    #ports:
    volumes:
      - ${HOME_DOCKER_CONFIG}/ollama/code:/code
      - ${HOME_DOCKER_CONFIG}/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - internal_services
```

But, no classifcation is happening?

These are the logs from the startup of ActualBudget-ai:
```
docker logs actualbudget-actual-ai-1 -f
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

> @sakowicz/actual-ai@1.8.0 prod
> node dist/app.js

Creating model for provider: ollama
Application started
Starting classification process
(node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Loading fresh spreadsheet
Syncing since 2025-03-20T15:02:05.922Z-0000-0000000000000000 0 (attempt: 0)
Got messages from server 0
Syncing since 1970-01-01T00:00:00.000Z-0000-0000000000000000 0 (attempt: 1)
Got messages from server 5506
Budget downloaded
Syncing since 2025-03-20T15:07:06.072Z-009E-bcd1f26322881eba 0 (attempt: 0)
Got messages from server 0
```

And, this is my running ollama-container logs:
```
llama_init_from_model:        CPU compute buffer size =   428.01 MiB
llama_init_from_model: graph nodes  = 1286
llama_init_from_model: graph splits = 1
time=2025-03-20T14:35:48.945Z level=INFO source=server.go:619 msg="llama runner started in 3.02 seconds"
[GIN] 2025/03/20 - 14:35:48 | 200 |  3.480556794s |       127.0.0.1 | POST     "/api/generate"

```
So, it seems it never connects to the ollama-container?

I've tried pinging the ollama container, and tried a curl-command from the actual-ai docker. When I do that I see the requests being logged in the ollama container. So the connection is there, but it seems the communication/connection to actually classify anything never happens - is there some way I could enable more debugging or manually force a classification?

**Comment by sakowicz** [comment]
It looks like there are no uncategorized transactions in actual-budget. Strange. Can it be a case?

Can you try the latest release as there are more debug logs?

**Comment by smathev** [comment]
Thank you for your patience. I updated the docker using this compose-file:
```
name: actualbudget

include:
  - path: ../config/networks.yml

services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    networks:
      - internal_services
    volumes:
      - ${HOME_DOCKER_CONFIG}/actualbudget/actual-data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    labels:
      caddy-int: ${ACTUALBUDGET_DOMAIN}
      caddy-int.reverse_proxy: "{{upstreams 5006}}"
      caddy-int.tls: internal

  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    restart: unless-stopped
    networks:
      - internal_services
    environment:
      ACTUAL_SERVER_URL: ${ACTUAL_SERVER_URL}
      ACTUAL_PASSWORD: ${ACTUAL_PASSWORD}
      ACTUAL_BUDGET_ID: ${ACTUAL_BUDGET_ID}
      CLASSIFICATION_SCHEDULE_CRON: ${CLASSIFICATION_SCHEDULE_CRON}
      FEATURES: '["classifyOnStartup", "syncAccountsBeforeClassify", "freeWebSearch", "suggestNewCategories"]'
      LLM_PROVIDER: ${LLM_PROVIDER}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
```

These are my latest logs from the ActualBudget-AI:
```
Creating model for provider: ollama
Set ollama rate limits: 50 requests/minute, 10000 tokens/minute
Application started
Starting classification process
Loading fresh spreadsheet
Syncing since 2025-03-20T19:28:23.143Z-0000-921dc9ea97e7b779 0 (attempt: 0)
Got messages from server 224
Budget downloaded
Syncing bank accounts
Bank accounts synced
Found 22 transaction categorization rules
rerunMissedTransactions false
No uncategorized transactions to process
Syncing since 2025-03-26T09:48:54.951Z-00DF-941ce8b32a1412c6 0 (attempt: 0)
Got messages from server 0
npm error path /opt/node_app/app
npm error command failed
npm error signal SIGTERM
npm error command sh -c node dist/app.js
npm error A complete log of this run can be found in: /home/node/.npm/_logs/2025-03-26T09_48_53_615Z-debug-0.log
> @sakowicz/actual-ai@2.0.0 prod
> node dist/app.js
Creating model for provider: ollama
Set ollama rate limits: 50 requests/minute, 10000 tokens/minute
Application started
Starting classification process
Loaded spreadsheet from cache (8513 items)
Syncing since 2025-03-26T09:48:54.951Z-00DF-941ce8b32a1412c6 0 (attempt: 0)
Got messages from server 0
Budget downloaded
Syncing bank accounts
Bank accounts synced
Found 22 transaction categorization rules
rerunMissedTransactions false
No uncategorized transactions to process
Syncing since 2025-03-26T09:48:54.951Z-00DF-941ce8b32a1412c6 0 (attempt: 0)
Got messages from server 0
```
As you see I've also tried a restart of the server, to force an attempt at categorizing.

In my actualBudget webpage I have 27 uncategorized transfers right now.

Let me know what else I can do, is there a setting to make the logging more verbose I need to enable?
