### ISSUE TITLE
Got messages from server 0 when trying to categorize any transaction

### ISSUE THREAD

**Issue by brandons209** [sakowicz/actual-ai#223]
Hello! I am new to actual budget, and I am trying to setup AI categorization using a local ollama server. Currently, no matter what model I use, the model failed to categorize any transaction and always returns an actual-ai-miss.

Logs:
```
actual_server-1  | Checking if there are any migrations to run for direction "up"...
actual_server-1  | Migrations: DONE
actual-ai-1      | 
actual-ai-1      | > @sakowicz/actual-ai@2.0.4 prod
actual-ai-1      | > node dist/app.js
actual-ai-1      | 
actual_server-1  | Running in production mode - Serving static React app
actual_server-1  | Listening on :::5006...
actual-ai-1      | Creating model for provider: ollama
actual-ai-1      | Set ollama rate limits: 50 requests/minute, 10000 tokens/minute
actual-ai-1      | Application started
actual-ai-1      | Starting classification process
actual_server-1  | Logging in via password
actual_server-1  | Deleted 0 old sessions
actual_server-1  | 2025-04-12T22:07:49.268Z info: POST 200 /account/login
actual_server-1  | 2025-04-12T22:07:49.363Z info: POST 200 /sync/user-get-key
actual-ai-1      | Loaded spreadsheet from cache (1233 items)
actual-ai-1      | Syncing since 2025-04-12T22:01:06.149Z-0000-8e74a7115b2d3a95 0 (attempt: 0)
actual_server-1  | 2025-04-12T22:07:49.626Z info: POST 200 /sync/sync
actual-ai-1      | Got messages from server 0
actual-ai-1      | Budget downloaded
actual-ai-1      | Syncing bank accounts
actual_server-1  | 2025-01-13 - 2025-05-01
actual_server-1  | 2025-04-12T22:07:55.741Z info: POST 200 /simplefin/transactions
actual-ai-1      | Bank accounts synced
actual-ai-1      | === DRY RUN MODE ===
actual-ai-1      | No changes will be made to transactions or categories
actual-ai-1      | =====================
actual-ai-1      | Found 0 transaction categorization rules
actual-ai-1      | rerunMissedTransactions true
actual-ai-1      | All transactions count: 197
actual-ai-1      | All accounts: 9
actual-ai-1      | Accounts off budget: 3
actual-ai-1      | Already has a category - Excluded 5 transactions
actual-ai-1      | Is starting balance - Excluded 3 transactions
actual-ai-1      | Account is not budget - Excluded 33 transactions
actual-ai-1      | Found 156 uncategorized transactions
actual-ai-1      | Processing batch 1 (transactions 1-20)
actual-ai-1      | 1/156 Processing transaction '***'
actual-ai-1      | Making LLM request to ollama (fallback mode)
actual-ai-1      | Sending text generation request to ollama
actual-ai-1      | Syncing since 2025-04-12T22:01:06.149Z-0000-8e74a7115b2d3a95 8 (attempt: 0)
actual_server-1  | 2025-04-12T22:07:57.811Z info: POST 200 /sync/sync
actual-ai-1      | Got messages from server 0
actual-ai-1      | 2/156 Processing transaction '***'
actual-ai-1      | Making LLM request to ollama (fallback mode)
actual-ai-1      | Sending text generation request to ollama
actual-ai-1      | Syncing since 2025-04-12T22:07:56.686Z-0000-8e74a7115b2d3a95 1 (attempt: 0)
actual_server-1  | 2025-04-12T22:08:02.387Z info: POST 200 /sync/sync
actual-ai-1      | Got messages from server 0
actual-ai-1      | 3/156 Processing transaction '***'
actual-ai-1      | Making LLM request to ollama (fallback mode)
actual-ai-1      | Sending text generation request to ollama
actual-ai-1      | Syncing since 2025-04-12T22:08:01.224Z-0000-8e74a7115b2d3a95 1 (attempt: 0)
actual_server-1  | 2025-04-12T22:08:06.775Z info: POST 200 /sync/sync
actual-ai-1      | Got messages from server 0
actual-ai-1      | 4/156 Processing transaction '***'
actual-ai-1      | Making LLM request to ollama (fallback mode)
actual-ai-1      | Sending text generation request to ollama
actual-ai-1      | Syncing since 2025-04-12T22:08:05.637Z-0000-8e74a7115b2d3a95 1 (attempt: 0)
actual_server-1  | 2025-04-12T22:08:11.058Z info: POST 200 /sync/sync
actual-ai-1      | Got messages from server 0
actual-ai-1      | 5/156 Processing transaction '***'
actual-ai-1      | Making LLM request to ollama (fallback mode)
actual-ai-1      | Sending text generation request to ollama
actual-ai-1      | Syncing since 2025-04-12T22:08:09.932Z-0000-8e74a7115b2d3a95 1 (attempt: 0)
actual_server-1  | 2025-04-12T22:08:15.506Z info: POST 200 /sync/sync
actual-ai-1      | Got messages from server 0
```

Ollama shows that the calls are going through and being processed:
```
ollama            | [GIN] 2025/04/12 - 22:08:01 | 200 |  4.281438637s |   192.168.0.199 | POST     "/api/chat"
ollama            | [GIN] 2025/04/12 - 22:08:05 | 200 |  4.274545806s |   192.168.0.199 | POST     "/api/chat"
ollama            | [GIN] 2025/04/12 - 22:08:09 | 200 |  4.168494724s |   192.168.0.199 | POST     "/api/chat"
ollama            | [GIN] 2025/04/12 - 22:08:14 | 200 |  4.393362098s |   192.168.0.199 | POST     "/api/chat"
```
I've tried changing the prompt and it still never returns any messages.

Heres my docker config:
```
  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    restart: unless-stopped
    environment:
      ACTUAL_SERVER_URL: ***
      ACTUAL_PASSWORD: ***
      ACTUAL_BUDGET_ID: *** # This is the ID from Settings → Show advanced settings → Sync ID
      CLASSIFICATION_SCHEDULE_CRON: 0 */4 * * * # How often to run classification.
      LLM_PROVIDER: ollama # Can be "openai", "anthropic", "google-generative-ai", "ollama" or "groq"
      FEATURES: '["classifyOnStartup", "syncAccountsBeforeClassify", "freeWebSearch", "dryRun", "dryRunNewCategories", "suggestNewCategories", "rerunMissedTransactions"]'
      OLLAMA_MODEL: cogito:14b # optional. required if you want to use an Ollama specific model, default is "phi3.5"
      OLLAMA_BASE_URL: http://127.0.0.1:11434/api # optional. required for ollama provider
      ACTUAL_E2E_PASSWORD: *** # optional. required if you have E2E encryption
#      NODE_TLS_REJECT_UNAUTHORIZED: 0 # optional. required if you have trouble connecting to Actual server
      NOT_GUESSED_TAG: #actual-ai-miss
      GUESSED_TAG: #actual-ai
    depends_on:
      - actual_server
```

**Comment by Pl1997** [comment]
Hello,

I'm having exactly the same issue, I would be very interested to know how you'll solve this !

Thanks for your help

**Comment by razvangazi** [comment]
Hey, same issue here.

**Comment by jcbshw** [comment]
I am experiencing the same issue with a context window of 32768 is Ollama. If I do a dry run I get #actual-ai-miss on every transaction. Ollama logs are reporting no errors and working fine with other things like paperless-ai.

Here are my environment variables.

```
ACTUAL_SERVER_URL: http://actual:5006
ACTUAL_PASSWORD: $ACTUAL_PASSWORD
ACTUAL_BUDGET_ID: $ACTUAL_ID
CLASSIFICATION_SCHEDULE_CRON: 0 */4 * * * 
LLM_PROVIDER: ollama # Can be "openai", "anthropic", "google-generative-ai", "ollama" or "groq"
FEATURES: '["classifyOnStartup", "freeWebSearch", "suggestNewCategories"]'
OLLAMA_MODEL: hf.co/unsloth/phi-4-GGUF:Q4_K_M
OLLAMA_BASE_URL: http://ollama:11434/api
```

**Comment by Pl1997** [comment]
Hello ! I also tried to do it with the last version (by pulling :latest on docker this morning). I do not get any particular messages in actual-ai logs, neither in ollama. Furthermore, I tried a few days ago to run it along with Wireshark. It seems that ollama does receive the right request and sends back the expected answer... Let me know if I can provide anything useful to help with debugging !

**Comment by Pl1997** [comment]
I just tried it again, with Wireshark running on my ollama server machine ! Here is what is sent to ollama by actual-ai :

`{
    "model": "mistral",
    "options": {
        "temperature": 0.1
    },
    "messages": [
        {
            "content": "I want to categorize the given bank transaction.\n\nTransaction details:\n* Amount: 670\n* Type: Outcome\n* Description: CARTE 07/04 MAISON JULIEN PARIS-miss-miss #actual-ai-miss\n* Payee: Maison Julien Paris\n* Date: 2025-04-08\n\nExisting categories by group:\nGROUP: Usual Expenses (ID: \"fc3825fd-b982-4b72-b768-5b30844cf832\")\n* Food (ID: \"541836f1-e756-4473-a5d0-6c1d3f06c7fa\")\n* General (ID: \"af375fd4-d759-46b3-bffe-74a856151d57\")\n* Bills (ID: \"d4b0f075-3343-4408-91ed-fae94f74e5bf\")\n* Bills (Flexible) (ID: \"29ec2c58-8cd3-42fe-9187-7b5dfe0f70a6\")\nGROUP: Investments and Savings (ID: \"a137772f-cf2f-4089-9432-822d2ddc1466\")\n* Savings (ID: \"6bbd8472-25d4-4cee-8a11-5bd9f7e83d61\")\nGROUP: Income (ID: \"2E1F5BDB-209B-43F9-AF2C-3CE28E380C00\")\n* Income (ID: \"3c1699a5-522a-435e-86dc-93d900a14f0e\")\n* Starting Balances (ID: \"506e8d9d-7ed0-4397-84e4-07a9185dc6b2\")\n\n\nIMPORTANT: You MUST respond with ONLY a valid JSON object using this structure:\n{\n  \"type\": \"existing\"|\"new\"|\"rule\",\n  \"categoryId\": \"string\", // Required for existing category or rule match\n  \"ruleName\": \"string\", // Required if matching rule\n  \"newCategory\": { // Required if suggesting new category\n    \"name\": \"string\", \n    \"groupName\": \"string\",\n    \"groupIsNew\": boolean\n  }\n}\n\nDO NOT output any text before or after the JSON. Your entire response must be a valid, parsable JSON object.\n\nExamples:\n{\"type\": \"existing\", \"categoryId\": \"abc123\"}\n{\"type\": \"rule\", \"categoryId\": \"def456\", \"ruleName\": \"Coffee Shop\"}\n{\"type\": \"new\", \"newCategory\": {\"name\": \"Pet Supplies\", \"groupName\": \"Pets\", \"groupIsNew\": true}}\n\n",
            "role": "user"
        }
    ],
    "stream": false
}`

And here is what is sent back by ollama :

`{
    "model": "mistral",
    "created_at": "2025-04-19T11:07:53.620521Z",
    "message": {
        "role": "assistant",
        "content": " {\n  \"type\": \"existing\",\n  \"categoryId\": \"d4b0f075-3343-4408-91ed-fae94f74e5bf\"\n}"
    },
    "done_reason": "stop",
    "done": true,
    "total_duration": 11185294459,
    "load_duration": 17888709,
    "prompt_eval_count": 763,
    "prompt_eval_duration": 6548457208,
    "eval_count": 53,
    "eval_duration": 4617287333
}`

I'm only getting "actual-ai-misses" in DryRun mode.

**Comment by jcbshw** [comment]
I was able to get it working with Ollama by making a few changes.

https://github.com/sakowicz/actual-ai/blob/d52252761f807051050240447ac47ece7df3ea99/src/llm-service.ts#L74-L77
to
```
return parseLlmResponse(response);
```

and

https://github.com/sakowicz/actual-ai/blob/d52252761f807051050240447ac47ece7df3ea99/src/llm-service.ts#L114
to
```
return text.replace(/(\r\n|\n|\r)/gm, '');
```

Haven't looked to much into why Ollama is using it's own function "askUsingFallbackModel"

**Comment by Pl1997** [comment]
Hello ! I can confirm that I couldn't make it work with native ollama api. However, by using the openai endpoint, and by following the amazing suggestion of @sakowicz to increase the model window (see [https://github.com/ollama/ollama/issues/5965#issuecomment-2252354726](url)), I was able to make it work ! (Without the freeWebSearch tool though, see #231 )

**Comment by brandons209** [comment]
Thank you all! I haven't had a chance to follow up on this, I'll try using the OpenAI endpoint and see how that goes.

**Comment by fendyg** [comment]
Just in case it helps someone that ran into the same issues described above. Here's what fixed it for me (as alluded to by several others before me)  by setting up LLM provider as openai - pointing to Ollama’s OpenAI compatible API endpoint

```yaml
    LLM_PROVIDER: openai 
    OPENAI_BASE_URL: http://localhost:port/v1
    OPENAI_MODEL: gemma3:4b
```
