### ISSUE TITLE
When using categorizer-ai, Nordigen / GoCardless Rate Limit is constantly exceeded

### ISSUE THREAD

**Issue by delize** [sakowicz/actual-ai#59]
https://discord.com/channels/937901803608096828/1310670990803599460/1310670990803599460

I found that when using categorizer AI, I consistently hit a rate limit with GoCardless.

When using the following docker-compose configuration:

```
  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    restart: unless-stopped
    environment:
      - ACTUAL_SERVER_URL=http://actual_server:5006
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - ACTUAL_BUDGET_ID=${ACTUAL_BUDGET_ID} # This is the ID from Settings → Show advanced settings → Sync ID
      - CLASSIFICATION_SCHEDULE_CRON=0 0 */5 * * # How often to run classification.
      - CLASSIFY_ON_STARTUP=true # Whether to classify transactions on startup (don't wait for cron schedule)
      - SYNC_ACCOUNTS_BEFORE_CLASSIFY=true # Whether to sync accounts before classification
      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - OPENAI_MODEL= # optional. required if you want to use a specific model, default is "gpt-3.5-turbo-instruct"
#      - OPENAI_BASE_URL= # optional. required if you don't want to use the OpenAI API but OpenAI compatible API, ex: "http://ollama:11424/v1
      - ACTUAL_E2E_PASSWORD=${ACTUAL_E2E_PASS} # optional. required if you have E2E encryption
#      - NODE_TLS_REJECT_UNAUTHORIZED=0 # optional. required if you have trouble connecting to Actual server 
    networks:
      backend:
```

It seems like it would continually get stuck and exit the docker container. Once exited, it would constantly restart due to the method "unless-stopped" being specified. Which would then in turn, would have Nordigen continually run and resync.

The cron job was not being followed on an unsuccessful exit (even if failed).
